<main class="main">

   <div class="container-admin">

        <div class="acciones">
            <a href="<?= BASE_URL ?>formAgregarArticulo" type="button" class="boton-agregar">AGREGAR ARTICULO</a>
        </div>

        <table class="tabla-articulos">
            <tr>
                <th>ID</th>
                <th>NOMBRE</th>
                <th>MARCA</th>
                <th>MEMORIA</th>
                <th>PANTALLA</th>
                <th>CAMARA</th>
                <th>PRECIO</th>
                <th>STOCK</th>
                <th>ACCIONES</th>
            </tr>
            <?php foreach ($articulos as $articulo): ?>
                <tr>
                    <td><?php echo $articulo->id_articulo ?></td>
                    <td><?php echo $articulo->nombre ?></td>
                    <td><?php echo $articulo->nombre_marca ?></td>
                    <td><?php echo $articulo->memoria ?></td>
                    <td><?php echo $articulo->pantalla ?></td>
                    <td><?php echo $articulo->camara ?></td>
                    <td><?php echo $articulo->precio ?></td>
                    <td><?php echo $articulo->stock ?></td>
                    <td>
                        <div class="acciones-tabla">
                            <a href="<?= BASE_URL ?>formEditarArticulo/<?= $articulo->id_articulo ?>" type="button" class="boton-editar">EDITAR</a>
                            <a href="<?= BASE_URL ?>deleteArticulo/<?= $articulo->id_articulo ?>" type="button" class="boton-eliminar">ELIMINAR</a>
                        </div>
                    </td>

                </tr>
            <?php endforeach; ?>

        </table>

        <div class="acciones">
            <a href="<?= BASE_URL ?>formAgregarMarca" type="button" class="boton-agregar">AGREGAR MARCA</a>
        </div>

        <table class="tabla-marcas">
            <tr>
                <th>ID</th>
                <th>NOMBRE</th>
                <th>IMAGEN</th>
                <th>ACCIONES</th>
            </tr>
            <?php foreach ($marcas as $marca): ?>
                <tr>
                    <td><?php echo $marca->id_marca ?></td>
                    <td><?php echo $marca->nombre_marca ?></td>
                    <td><?php echo $marca->img_marca ?></td>
                    <td>
                        <div class="acciones-tabla">
                            <a href="<?= BASE_URL ?>formEditarMarca/<?= $marca->id_marca ?>" type="button" class="boton-editar">EDITAR</a>
                            <a href="<?= BASE_URL ?>deleteMarca/<?= $marca->id_marca ?>" type="button" class="boton-eliminar">ELIMINAR</a>
                        </div>
                    </td>

                </tr>
            <?php endforeach; ?>
        </table>

    </div>

</main>