<main class="main">

  <div class="principal">
    <div class="contenedor-celular">
      <div class="contenedor-imagen">
        <img src="<?= $celulares->img ?>" alt="">
      </div>
      <div class="info-celular">
        <h1><?= $celulares->nombre ?></h1>

        <p>MEMORIA: <?= $celulares->memoria ?> GB</p>
        <p>PANTALLA: <?= $celulares->pantalla ?>"</p>
        <p>CAMARA: <?= $celulares->camara ?> MP</p>
        <p>PRECIO: $<?= $celulares->precio ?></p>
        <p>MARCA: <?= $celulares->nombre_marca ?></p>

      
      </div>
    </div>
  </div>
</main>