<div class="container-login">
    <h2>Login Form</h2>
    <form action="login" method="post">
        <div class="container-form">
            <label for="usuario">Username</label>
            <input type="text" placeholder="Enter Username" id="usuario" name="usuario" required>

            <label for="contraseña">Password</label>
            <input type="password" placeholder="Enter Password" id="contraseña" name="contraseña" required>
            
            <button type="submit">Login</button>
        </div>
    </form>
</div>